api_platform:
    title: 'Tell Hatarah Database API'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources','%kernel.project_dir%/src/Entity']
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
