api_platform:
    title: 'LoNAP excavation database API'
    version: '0.1'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    defaults:
        pagination_client_enabled: true
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
            enabled_parameter_name: pagination
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    enable_swagger_ui: true
    enable_entrypoint: true

when@prod:
    api_platform:
        enable_swagger_ui: false
