vich_uploader:
    db_driver: orm

    mappings:
      media_object:
        uri_prefix: /media
        # upload_destination: '%kernel.project_dir%/public/media'
        upload_destination: /srv/static
        # Will rename uploaded files using a uniqueid as a prefix.
        #namer: Vich\UploaderBundle\Naming\OrignameNamer
        #namer: App\Service\MediaObjectFileHashNamer
        namer: app.media_object_file_hash_namer
        directory_namer: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
