version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ${WWW_STATIC_DIR}:/srv/static
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      - DATABASE_URL=${DATABASE_URL}
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - php
    ports:
      - ${NGINX_PORT:-8000}:80
    volumes:
      - .:/srv/api
      - ${WWW_STATIC_DIR}:/srv/static:ro
      - ${WWW_CLIENT_DIR}:/srv/client:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/certbot/www:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
      - ./var/log/nginx:/var/log/nginx
      - php_socket:/var/run/php
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw
    logging:
      driver: local
      options:
        max-size: "5m"
        max-file: "2"
###> doctrine/doctrine-bundle ###
  database:
    image: postgis/postgis:13-3.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB:-thad}
        #    ports:
        #- ${POSTGRES_PORT:-5432}:5432
    restart: unless-stopped
    volumes:
      - ./docker/database/bin/dump_thad.sh:/usr/local/bin/dump_thad.sh:ro
      - ${POSTGRES_DUMP_DIR}:/data/dump:rw
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
###< doctrine/doctrine-bundle ###

volumes:
  php_socket:
###> doctrine/doctrine-bundle ###
#  db-data:
###< doctrine/doctrine-bundle ###
