version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    ports:
      - ${NGINX_PORT:-80}:80
      - ${NGINX_SSL_PORT:-443}:443
    volumes:
      - ./docker/nginx/templates/site.conf.prod.template:/etc/nginx/templates/site.conf.template
