version: '3.4'

services:
  php:
    volumes:
      - .:/srv/api:rw,cached
      - ./docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      - ./var:/srv/api/var:rw
    environment:
      APP_ENV: dev
  nginx:
    volumes:
      - ./docker/nginx/templates/site.conf.dev.template:/etc/nginx/templates/site.conf.template
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###
