version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      - DATABASE_URL=${DATABASE_URL}
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - php_socket:/var/run/php
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
###< doctrine/doctrine-bundle ###

volumes:
  php_socket:
###> doctrine/doctrine-bundle ###
#  db-data:
###< doctrine/doctrine-bundle ###
