<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220517155858 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA geom');
        $this->addSql('CREATE SEQUENCE area_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cumulative_pottery_sheet_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ecofact_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE media_object_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE media_objects__sus_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pottery_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sample_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE geom.site_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE small_find_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE stratigraphic_relationships_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE su_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE geom.su_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__decoration_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__e__type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__o__colour_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__o__material_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__o__preservation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__o__type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__base_shape_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__body_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__colour_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__fabric_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__firing_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__handle_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__manufacturing_technique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__neck_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__neck_length_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__preservation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__rim_characterization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__rim_direction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__rim_shape_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__size_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__spout_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__surface_characteristic_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__surface_treatment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__vessel_shape_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__p__ware_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__period_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__preservation_state_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__s__type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voc__su__type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE area (id INT NOT NULL, site_id INT DEFAULT NULL, code VARCHAR(3) NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D7943D68F6BD1646 ON area (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7943D68F6BD164677153098 ON area (site_id, code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7943D68F6BD16465E237E06 ON area (site_id, name)');
        $this->addSql('CREATE TABLE cumulative_pottery_sheet (id INT NOT NULL, su_id INT NOT NULL, date DATE NOT NULL, number SMALLINT NOT NULL, compiler VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, common_ware_non_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, common_ware_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, fire_ware_non_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, fire_ware_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, coarse_ware_non_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, coarse_ware_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, kitchen_ware_non_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, kitchen_ware_diagnostic_count SMALLINT DEFAULT 0 NOT NULL, subperiod_epn_count SMALLINT DEFAULT 0 NOT NULL, subperiod_has_count SMALLINT DEFAULT 0 NOT NULL, subperiod_sam_count SMALLINT DEFAULT 0 NOT NULL, subperiod_hal_count SMALLINT DEFAULT 0 NOT NULL, subperiod_nub_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lca_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lca1_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lca2_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lca3_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lca4_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lca5_count SMALLINT DEFAULT 0 NOT NULL, subperiod_sur_count SMALLINT DEFAULT 0 NOT NULL, subperiod_emt_count SMALLINT DEFAULT 0 NOT NULL, subperiod_emt1_count SMALLINT DEFAULT 0 NOT NULL, subperiod_emt2_count SMALLINT DEFAULT 0 NOT NULL, subperiod_emt3_count SMALLINT DEFAULT 0 NOT NULL, subperiod_emt4_count SMALLINT DEFAULT 0 NOT NULL, subperiod_emt5_count SMALLINT DEFAULT 0 NOT NULL, subperiod_mba_count SMALLINT DEFAULT 0 NOT NULL, subperiod_mba1_count SMALLINT DEFAULT 0 NOT NULL, subperiod_mba2_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lba_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lba1_count SMALLINT DEFAULT 0 NOT NULL, subperiod_lba2_count SMALLINT DEFAULT 0 NOT NULL, subperiod_ira_count SMALLINT DEFAULT 0 NOT NULL, subperiod_ira1_count SMALLINT DEFAULT 0 NOT NULL, subperiod_ira2_count SMALLINT DEFAULT 0 NOT NULL, subperiod_hel_count SMALLINT DEFAULT 0 NOT NULL, subperiod_par_count SMALLINT DEFAULT 0 NOT NULL, subperiod_byz_count SMALLINT DEFAULT 0 NOT NULL, subperiod_sas_count SMALLINT DEFAULT 0 NOT NULL, subperiod_isl_count SMALLINT DEFAULT 0 NOT NULL, subperiod_isl1_count SMALLINT DEFAULT 0 NOT NULL, subperiod_isl2_count SMALLINT DEFAULT 0 NOT NULL, subperiod_isl3_count SMALLINT DEFAULT 0 NOT NULL, subperiod_undetermined_count SMALLINT DEFAULT 0 NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DB90ABFCBDB1218E ON cumulative_pottery_sheet (su_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DB90ABFCBDB1218E96901F54 ON cumulative_pottery_sheet (su_id, number)');
        $this->addSql('COMMENT ON COLUMN cumulative_pottery_sheet.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE ecofact (id INT NOT NULL, su_id INT NOT NULL, type_id SMALLINT NOT NULL, preservation_state_id SMALLINT DEFAULT NULL, date DATE NOT NULL, number SMALLINT NOT NULL, height DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, thickness DOUBLE PRECISION DEFAULT NULL, min_diameter DOUBLE PRECISION DEFAULT NULL, max_diameter DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, selected_for_analysis BOOLEAN NOT NULL, compiler VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9F00A5DDBDB1218E ON ecofact (su_id)');
        $this->addSql('CREATE INDEX IDX_9F00A5DDC54C8C93 ON ecofact (type_id)');
        $this->addSql('CREATE INDEX IDX_9F00A5DDFE71FA16 ON ecofact (preservation_state_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F00A5DDBDB1218E96901F54 ON ecofact (su_id, number)');
        $this->addSql('COMMENT ON COLUMN ecofact.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE media_object (id INT NOT NULL, file_path VARCHAR(255) NOT NULL, mime_type VARCHAR(64) NOT NULL, size INT NOT NULL, width SMALLINT DEFAULT NULL, height SMALLINT DEFAULT NULL, sha256 CHAR(64) NOT NULL, upload_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_14D431325CC814F7 ON media_object (sha256)');
        $this->addSql('COMMENT ON COLUMN media_object.upload_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE media_objects__sus (id INT NOT NULL, su_id INT DEFAULT NULL, media_object_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF40F0ECBDB1218E ON media_objects__sus (su_id)');
        $this->addSql('CREATE INDEX IDX_BF40F0EC64DE5A5 ON media_objects__sus (media_object_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BF40F0ECBDB1218E64DE5A5 ON media_objects__sus (su_id, media_object_id)');
        $this->addSql('CREATE TABLE pottery (id INT NOT NULL, su_id INT NOT NULL, period_id SMALLINT DEFAULT NULL, ext_surface_color_id SMALLINT DEFAULT NULL, int_surface_color_id SMALLINT DEFAULT NULL, fracture_color_id SMALLINT DEFAULT NULL, ware_id SMALLINT DEFAULT NULL, fabric_id SMALLINT DEFAULT NULL, surface_characteristic_id SMALLINT DEFAULT NULL, surface_treatment_id SMALLINT DEFAULT NULL, manufacturing_technique_id SMALLINT DEFAULT NULL, firing_id SMALLINT DEFAULT NULL, decoration_id SMALLINT DEFAULT NULL, vessel_shape_id SMALLINT DEFAULT NULL, rim_shape_id SMALLINT DEFAULT NULL, rim_direction_id SMALLINT DEFAULT NULL, rim_characterization_id SMALLINT DEFAULT NULL, neck_id SMALLINT DEFAULT NULL, neck_length_id SMALLINT DEFAULT NULL, body_id SMALLINT DEFAULT NULL, handle_id SMALLINT DEFAULT NULL, spout_id SMALLINT DEFAULT NULL, size_group_id SMALLINT DEFAULT NULL, base_shape_id SMALLINT DEFAULT NULL, preservation_id SMALLINT DEFAULT NULL, number SMALLINT NOT NULL, thickness DOUBLE PRECISION DEFAULT NULL, rim_diameter DOUBLE PRECISION DEFAULT NULL, base_diameter DOUBLE PRECISION DEFAULT NULL, date DATE NOT NULL, compiler VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1A651839BDB1218E ON pottery (su_id)');
        $this->addSql('CREATE INDEX IDX_1A651839EC8B7ADE ON pottery (period_id)');
        $this->addSql('CREATE INDEX IDX_1A651839AD1FCB98 ON pottery (ext_surface_color_id)');
        $this->addSql('CREATE INDEX IDX_1A651839F0B7C66A ON pottery (int_surface_color_id)');
        $this->addSql('CREATE INDEX IDX_1A651839ABB639B3 ON pottery (fracture_color_id)');
        $this->addSql('CREATE INDEX IDX_1A65183961E14598 ON pottery (ware_id)');
        $this->addSql('CREATE INDEX IDX_1A651839AB43EC50 ON pottery (fabric_id)');
        $this->addSql('CREATE INDEX IDX_1A651839479088F4 ON pottery (surface_characteristic_id)');
        $this->addSql('CREATE INDEX IDX_1A651839EFB04BBB ON pottery (surface_treatment_id)');
        $this->addSql('CREATE INDEX IDX_1A6518395D832DFC ON pottery (manufacturing_technique_id)');
        $this->addSql('CREATE INDEX IDX_1A6518394B2BD234 ON pottery (firing_id)');
        $this->addSql('CREATE INDEX IDX_1A6518393446DFC4 ON pottery (decoration_id)');
        $this->addSql('CREATE INDEX IDX_1A651839DD564C42 ON pottery (vessel_shape_id)');
        $this->addSql('CREATE INDEX IDX_1A65183924CBC30C ON pottery (rim_shape_id)');
        $this->addSql('CREATE INDEX IDX_1A651839414A8D6D ON pottery (rim_direction_id)');
        $this->addSql('CREATE INDEX IDX_1A651839DEBFB82A ON pottery (rim_characterization_id)');
        $this->addSql('CREATE INDEX IDX_1A651839B5691792 ON pottery (neck_id)');
        $this->addSql('CREATE INDEX IDX_1A65183966E3E996 ON pottery (neck_length_id)');
        $this->addSql('CREATE INDEX IDX_1A6518399B621D84 ON pottery (body_id)');
        $this->addSql('CREATE INDEX IDX_1A6518399C256C9C ON pottery (handle_id)');
        $this->addSql('CREATE INDEX IDX_1A6518391E5860E8 ON pottery (spout_id)');
        $this->addSql('CREATE INDEX IDX_1A651839A06F4D9B ON pottery (size_group_id)');
        $this->addSql('CREATE INDEX IDX_1A6518391ACDCF43 ON pottery (base_shape_id)');
        $this->addSql('CREATE INDEX IDX_1A651839B806376B ON pottery (preservation_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1A651839BDB1218E96901F54 ON pottery (su_id, number)');
        $this->addSql('COMMENT ON COLUMN pottery.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE sample (id INT NOT NULL, su_id INT NOT NULL, type_id SMALLINT NOT NULL, preservation_state_id SMALLINT DEFAULT NULL, date DATE NOT NULL, number SMALLINT NOT NULL, height DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, thickness DOUBLE PRECISION DEFAULT NULL, min_diameter DOUBLE PRECISION DEFAULT NULL, max_diameter DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, selected_for_analysis BOOLEAN NOT NULL, compiler VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, exhaustive BOOLEAN DEFAULT NULL, contamination_risk BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F10B76C3BDB1218E ON sample (su_id)');
        $this->addSql('CREATE INDEX IDX_F10B76C3C54C8C93 ON sample (type_id)');
        $this->addSql('CREATE INDEX IDX_F10B76C3FE71FA16 ON sample (preservation_state_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F10B76C3BDB1218E96901F54 ON sample (su_id, number)');
        $this->addSql('COMMENT ON COLUMN sample.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE geom.site (id INT NOT NULL, site_id INT DEFAULT NULL, geom geometry(MULTIPOLYGON, 4326) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9623109F6BD1646 ON geom.site (site_id)');
        $this->addSql('CREATE TABLE site (id INT NOT NULL, code VARCHAR(3) NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_694309E45E237E06 ON site (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_694309E477153098 ON site (code)');
        $this->addSql('CREATE TABLE small_find (id INT NOT NULL, su_id INT NOT NULL, material_id SMALLINT NOT NULL, type_id SMALLINT NOT NULL, preservation_id SMALLINT NOT NULL, preservation_state_id SMALLINT DEFAULT NULL, decoration_id SMALLINT DEFAULT NULL, ext_surface_color_id SMALLINT DEFAULT NULL, int_surface_color_id SMALLINT DEFAULT NULL, fracture_color_id SMALLINT DEFAULT NULL, date DATE NOT NULL, number SMALLINT NOT NULL, height DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, min_width DOUBLE PRECISION DEFAULT NULL, max_width DOUBLE PRECISION DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, thickness DOUBLE PRECISION DEFAULT NULL, min_diameter DOUBLE PRECISION DEFAULT NULL, max_diameter DOUBLE PRECISION DEFAULT NULL, base_diameter DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, compiler VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, summary TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2E109A89BDB1218E ON small_find (su_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89E308AC6F ON small_find (material_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89C54C8C93 ON small_find (type_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89B806376B ON small_find (preservation_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89FE71FA16 ON small_find (preservation_state_id)');
        $this->addSql('CREATE INDEX IDX_2E109A893446DFC4 ON small_find (decoration_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89AD1FCB98 ON small_find (ext_surface_color_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89F0B7C66A ON small_find (int_surface_color_id)');
        $this->addSql('CREATE INDEX IDX_2E109A89ABB639B3 ON small_find (fracture_color_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2E109A89BDB1218E96901F54 ON small_find (su_id, number)');
        $this->addSql('COMMENT ON COLUMN small_find.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE stratigraphic_relationships (id INT NOT NULL, sx_su_id INT DEFAULT NULL, dx_su_id INT DEFAULT NULL, relationship_id CHAR(1) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B9A4EF171E31BBE7 ON stratigraphic_relationships (sx_su_id)');
        $this->addSql('CREATE INDEX IDX_B9A4EF17684F83D5 ON stratigraphic_relationships (dx_su_id)');
        $this->addSql('CREATE INDEX IDX_B9A4EF172C41D668 ON stratigraphic_relationships (relationship_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9A4EF171E31BBE7684F83D5 ON stratigraphic_relationships (sx_su_id, dx_su_id)');
        $this->addSql('CREATE TABLE su (id INT NOT NULL, site_id INT NOT NULL, area_id INT NOT NULL, period_id SMALLINT DEFAULT NULL, type_id SMALLINT NOT NULL, preservation_state_id SMALLINT DEFAULT NULL, number INT NOT NULL, year INT NOT NULL, date DATE NOT NULL, description TEXT DEFAULT NULL, interpretation TEXT DEFAULT NULL, summary TEXT DEFAULT NULL, top_elevation DOUBLE PRECISION DEFAULT NULL, bottom_elevation DOUBLE PRECISION DEFAULT NULL, area_supervisor VARCHAR(255) DEFAULT NULL, compiler VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_65A4BD79F6BD1646 ON su (site_id)');
        $this->addSql('CREATE INDEX IDX_65A4BD79BD0F409C ON su (area_id)');
        $this->addSql('CREATE INDEX IDX_65A4BD79EC8B7ADE ON su (period_id)');
        $this->addSql('CREATE INDEX IDX_65A4BD79C54C8C93 ON su (type_id)');
        $this->addSql('CREATE INDEX IDX_65A4BD79FE71FA16 ON su (preservation_state_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_65A4BD79F6BD164696901F54 ON su (site_id, number)');
        $this->addSql('COMMENT ON COLUMN su.date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('CREATE TABLE geom.su (id INT NOT NULL, su_id INT DEFAULT NULL, geom geometry(MULTIPOLYGON, 4326) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FC438D2BDB1218E ON geom.su (su_id)');
        $this->addSql('CREATE TABLE "user" (uuid UUID NOT NULL, email VARCHAR(180) NOT NULL, roles TEXT NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(uuid))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('COMMENT ON COLUMN "user".uuid IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "user".roles IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE voc__decoration (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DB4299B81D775834 ON voc__decoration (value)');
        $this->addSql('CREATE TABLE voc__e__type (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B3C59741D775834 ON voc__e__type (value)');
        $this->addSql('CREATE TABLE voc__o__colour (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_877B36AC1D775834 ON voc__o__colour (value)');
        $this->addSql('CREATE TABLE voc__o__material (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D917017D1D775834 ON voc__o__material (value)');
        $this->addSql('CREATE TABLE voc__o__preservation (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EF9A46BE1D775834 ON voc__o__preservation (value)');
        $this->addSql('CREATE TABLE voc__o__type (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF4C063A1D775834 ON voc__o__type (value)');
        $this->addSql('CREATE TABLE voc__p__base_shape (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_32A3748D1D775834 ON voc__p__base_shape (value)');
        $this->addSql('CREATE TABLE voc__p__body (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39ACB6861D775834 ON voc__p__body (value)');
        $this->addSql('CREATE TABLE voc__p__colour (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F402BB0C1D775834 ON voc__p__colour (value)');
        $this->addSql('CREATE TABLE voc__p__fabric (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6319AE611D775834 ON voc__p__fabric (value)');
        $this->addSql('CREATE TABLE voc__p__firing (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B2FAC701D775834 ON voc__p__firing (value)');
        $this->addSql('CREATE TABLE voc__p__handle (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F7AFE1B1D775834 ON voc__p__handle (value)');
        $this->addSql('CREATE TABLE voc__p__manufacturing_technique (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F2D5EE21D775834 ON voc__p__manufacturing_technique (value)');
        $this->addSql('CREATE TABLE voc__p__neck (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C2156B671D775834 ON voc__p__neck (value)');
        $this->addSql('CREATE TABLE voc__p__neck_length (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A028CABC1D775834 ON voc__p__neck_length (value)');
        $this->addSql('CREATE TABLE voc__p__preservation (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF701A6C1D775834 ON voc__p__preservation (value)');
        $this->addSql('CREATE TABLE voc__p__rim_characterization (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BDAA3201D775834 ON voc__p__rim_characterization (value)');
        $this->addSql('CREATE TABLE voc__p__rim_direction (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FAD6D6011D775834 ON voc__p__rim_direction (value)');
        $this->addSql('CREATE TABLE voc__p__rim_shape (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BAB6A1C1D775834 ON voc__p__rim_shape (value)');
        $this->addSql('CREATE TABLE voc__p__size_group (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EEA89C751D775834 ON voc__p__size_group (value)');
        $this->addSql('CREATE TABLE voc__p__spout (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7492891D1D775834 ON voc__p__spout (value)');
        $this->addSql('CREATE TABLE voc__p__surface_characteristic (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_873DCB111D775834 ON voc__p__surface_characteristic (value)');
        $this->addSql('CREATE TABLE voc__p__surface_treatment (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B449A6991D775834 ON voc__p__surface_treatment (value)');
        $this->addSql('CREATE TABLE voc__p__vessel_shape (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE06866D1D775834 ON voc__p__vessel_shape (value)');
        $this->addSql('CREATE TABLE voc__p__ware (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C6CD5B91D775834 ON voc__p__ware (value)');
        $this->addSql('CREATE TABLE voc__period (id SMALLINT NOT NULL, parent_id SMALLINT DEFAULT NULL, code VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_15F30C99727ACA70 ON voc__period (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15F30C991D775834 ON voc__period (value)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15F30C9977153098 ON voc__period (code)');
        $this->addSql('CREATE TABLE voc__preservation_state (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B54DB031D775834 ON voc__preservation_state (value)');
        $this->addSql('CREATE TABLE voc__s__type (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F32F0801D775834 ON voc__s__type (value)');
        $this->addSql('CREATE TABLE voc__su__relationship (id CHAR(1) NOT NULL, inverted_by_id CHAR(1) DEFAULT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DB01D41C4CDAD40 ON voc__su__relationship (inverted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DB01D411D775834 ON voc__su__relationship (value)');
        $this->addSql('CREATE TABLE voc__su__type (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15EFB60B1D775834 ON voc__su__type (value)');
        $this->addSql('ALTER TABLE area ADD CONSTRAINT FK_D7943D68F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cumulative_pottery_sheet ADD CONSTRAINT FK_DB90ABFCBDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ecofact ADD CONSTRAINT FK_9F00A5DDBDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ecofact ADD CONSTRAINT FK_9F00A5DDC54C8C93 FOREIGN KEY (type_id) REFERENCES voc__e__type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ecofact ADD CONSTRAINT FK_9F00A5DDFE71FA16 FOREIGN KEY (preservation_state_id) REFERENCES voc__preservation_state (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_objects__sus ADD CONSTRAINT FK_BF40F0ECBDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_objects__sus ADD CONSTRAINT FK_BF40F0EC64DE5A5 FOREIGN KEY (media_object_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839BDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839EC8B7ADE FOREIGN KEY (period_id) REFERENCES voc__period (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839AD1FCB98 FOREIGN KEY (ext_surface_color_id) REFERENCES voc__p__colour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839F0B7C66A FOREIGN KEY (int_surface_color_id) REFERENCES voc__p__colour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839ABB639B3 FOREIGN KEY (fracture_color_id) REFERENCES voc__p__colour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A65183961E14598 FOREIGN KEY (ware_id) REFERENCES voc__p__ware (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839AB43EC50 FOREIGN KEY (fabric_id) REFERENCES voc__p__fabric (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839479088F4 FOREIGN KEY (surface_characteristic_id) REFERENCES voc__p__surface_characteristic (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839EFB04BBB FOREIGN KEY (surface_treatment_id) REFERENCES voc__p__surface_treatment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518395D832DFC FOREIGN KEY (manufacturing_technique_id) REFERENCES voc__p__manufacturing_technique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518394B2BD234 FOREIGN KEY (firing_id) REFERENCES voc__p__firing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518393446DFC4 FOREIGN KEY (decoration_id) REFERENCES voc__decoration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839DD564C42 FOREIGN KEY (vessel_shape_id) REFERENCES voc__p__vessel_shape (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A65183924CBC30C FOREIGN KEY (rim_shape_id) REFERENCES voc__p__rim_shape (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839414A8D6D FOREIGN KEY (rim_direction_id) REFERENCES voc__p__rim_direction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839DEBFB82A FOREIGN KEY (rim_characterization_id) REFERENCES voc__p__rim_characterization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839B5691792 FOREIGN KEY (neck_id) REFERENCES voc__p__neck (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A65183966E3E996 FOREIGN KEY (neck_length_id) REFERENCES voc__p__neck_length (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518399B621D84 FOREIGN KEY (body_id) REFERENCES voc__p__body (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518399C256C9C FOREIGN KEY (handle_id) REFERENCES voc__p__handle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518391E5860E8 FOREIGN KEY (spout_id) REFERENCES voc__p__spout (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839A06F4D9B FOREIGN KEY (size_group_id) REFERENCES voc__p__size_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A6518391ACDCF43 FOREIGN KEY (base_shape_id) REFERENCES voc__p__base_shape (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pottery ADD CONSTRAINT FK_1A651839B806376B FOREIGN KEY (preservation_id) REFERENCES voc__p__preservation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sample ADD CONSTRAINT FK_F10B76C3BDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sample ADD CONSTRAINT FK_F10B76C3C54C8C93 FOREIGN KEY (type_id) REFERENCES voc__s__type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sample ADD CONSTRAINT FK_F10B76C3FE71FA16 FOREIGN KEY (preservation_state_id) REFERENCES voc__preservation_state (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE geom.site ADD CONSTRAINT FK_B9623109F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89BDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89E308AC6F FOREIGN KEY (material_id) REFERENCES voc__o__material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89C54C8C93 FOREIGN KEY (type_id) REFERENCES voc__o__type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89B806376B FOREIGN KEY (preservation_id) REFERENCES voc__o__preservation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89FE71FA16 FOREIGN KEY (preservation_state_id) REFERENCES voc__preservation_state (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A893446DFC4 FOREIGN KEY (decoration_id) REFERENCES voc__decoration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89AD1FCB98 FOREIGN KEY (ext_surface_color_id) REFERENCES voc__o__colour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89F0B7C66A FOREIGN KEY (int_surface_color_id) REFERENCES voc__o__colour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE small_find ADD CONSTRAINT FK_2E109A89ABB639B3 FOREIGN KEY (fracture_color_id) REFERENCES voc__o__colour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stratigraphic_relationships ADD CONSTRAINT FK_B9A4EF171E31BBE7 FOREIGN KEY (sx_su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stratigraphic_relationships ADD CONSTRAINT FK_B9A4EF17684F83D5 FOREIGN KEY (dx_su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stratigraphic_relationships ADD CONSTRAINT FK_B9A4EF172C41D668 FOREIGN KEY (relationship_id) REFERENCES voc__su__relationship (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE su ADD CONSTRAINT FK_65A4BD79F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE su ADD CONSTRAINT FK_65A4BD79BD0F409C FOREIGN KEY (area_id) REFERENCES area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE su ADD CONSTRAINT FK_65A4BD79EC8B7ADE FOREIGN KEY (period_id) REFERENCES voc__period (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE su ADD CONSTRAINT FK_65A4BD79C54C8C93 FOREIGN KEY (type_id) REFERENCES voc__su__type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE su ADD CONSTRAINT FK_65A4BD79FE71FA16 FOREIGN KEY (preservation_state_id) REFERENCES voc__preservation_state (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE geom.su ADD CONSTRAINT FK_4FC438D2BDB1218E FOREIGN KEY (su_id) REFERENCES su (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voc__period ADD CONSTRAINT FK_15F30C99727ACA70 FOREIGN KEY (parent_id) REFERENCES voc__period (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voc__su__relationship ADD CONSTRAINT FK_2DB01D41C4CDAD40 FOREIGN KEY (inverted_by_id) REFERENCES voc__su__relationship (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE su DROP CONSTRAINT FK_65A4BD79BD0F409C');
        $this->addSql('ALTER TABLE media_objects__sus DROP CONSTRAINT FK_BF40F0EC64DE5A5');
        $this->addSql('ALTER TABLE area DROP CONSTRAINT FK_D7943D68F6BD1646');
        $this->addSql('ALTER TABLE geom.site DROP CONSTRAINT FK_B9623109F6BD1646');
        $this->addSql('ALTER TABLE su DROP CONSTRAINT FK_65A4BD79F6BD1646');
        $this->addSql('ALTER TABLE cumulative_pottery_sheet DROP CONSTRAINT FK_DB90ABFCBDB1218E');
        $this->addSql('ALTER TABLE ecofact DROP CONSTRAINT FK_9F00A5DDBDB1218E');
        $this->addSql('ALTER TABLE media_objects__sus DROP CONSTRAINT FK_BF40F0ECBDB1218E');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839BDB1218E');
        $this->addSql('ALTER TABLE sample DROP CONSTRAINT FK_F10B76C3BDB1218E');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89BDB1218E');
        $this->addSql('ALTER TABLE stratigraphic_relationships DROP CONSTRAINT FK_B9A4EF171E31BBE7');
        $this->addSql('ALTER TABLE stratigraphic_relationships DROP CONSTRAINT FK_B9A4EF17684F83D5');
        $this->addSql('ALTER TABLE geom.su DROP CONSTRAINT FK_4FC438D2BDB1218E');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518393446DFC4');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A893446DFC4');
        $this->addSql('ALTER TABLE ecofact DROP CONSTRAINT FK_9F00A5DDC54C8C93');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89AD1FCB98');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89F0B7C66A');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89ABB639B3');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89E308AC6F');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89B806376B');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89C54C8C93');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518391ACDCF43');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518399B621D84');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839AD1FCB98');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839F0B7C66A');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839ABB639B3');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839AB43EC50');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518394B2BD234');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518399C256C9C');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518395D832DFC');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839B5691792');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A65183966E3E996');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839B806376B');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839DEBFB82A');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839414A8D6D');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A65183924CBC30C');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839A06F4D9B');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A6518391E5860E8');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839479088F4');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839EFB04BBB');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839DD564C42');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A65183961E14598');
        $this->addSql('ALTER TABLE pottery DROP CONSTRAINT FK_1A651839EC8B7ADE');
        $this->addSql('ALTER TABLE su DROP CONSTRAINT FK_65A4BD79EC8B7ADE');
        $this->addSql('ALTER TABLE voc__period DROP CONSTRAINT FK_15F30C99727ACA70');
        $this->addSql('ALTER TABLE ecofact DROP CONSTRAINT FK_9F00A5DDFE71FA16');
        $this->addSql('ALTER TABLE sample DROP CONSTRAINT FK_F10B76C3FE71FA16');
        $this->addSql('ALTER TABLE small_find DROP CONSTRAINT FK_2E109A89FE71FA16');
        $this->addSql('ALTER TABLE su DROP CONSTRAINT FK_65A4BD79FE71FA16');
        $this->addSql('ALTER TABLE sample DROP CONSTRAINT FK_F10B76C3C54C8C93');
        $this->addSql('ALTER TABLE stratigraphic_relationships DROP CONSTRAINT FK_B9A4EF172C41D668');
        $this->addSql('ALTER TABLE voc__su__relationship DROP CONSTRAINT FK_2DB01D41C4CDAD40');
        $this->addSql('ALTER TABLE su DROP CONSTRAINT FK_65A4BD79C54C8C93');
        $this->addSql('DROP SEQUENCE area_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cumulative_pottery_sheet_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ecofact_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE media_object_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE media_objects__sus_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pottery_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sample_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE geom.site_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE small_find_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE stratigraphic_relationships_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE su_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE geom.su_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__decoration_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__e__type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__o__colour_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__o__material_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__o__preservation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__o__type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__base_shape_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__body_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__colour_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__fabric_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__firing_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__handle_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__manufacturing_technique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__neck_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__neck_length_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__preservation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__rim_characterization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__rim_direction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__rim_shape_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__size_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__spout_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__surface_characteristic_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__surface_treatment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__vessel_shape_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__p__ware_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__period_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__preservation_state_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__s__type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voc__su__type_id_seq CASCADE');
        $this->addSql('DROP TABLE area');
        $this->addSql('DROP TABLE cumulative_pottery_sheet');
        $this->addSql('DROP TABLE ecofact');
        $this->addSql('DROP TABLE media_object');
        $this->addSql('DROP TABLE media_objects__sus');
        $this->addSql('DROP TABLE pottery');
        $this->addSql('DROP TABLE sample');
        $this->addSql('DROP TABLE geom.site');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE small_find');
        $this->addSql('DROP TABLE stratigraphic_relationships');
        $this->addSql('DROP TABLE su');
        $this->addSql('DROP TABLE geom.su');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE voc__decoration');
        $this->addSql('DROP TABLE voc__e__type');
        $this->addSql('DROP TABLE voc__o__colour');
        $this->addSql('DROP TABLE voc__o__material');
        $this->addSql('DROP TABLE voc__o__preservation');
        $this->addSql('DROP TABLE voc__o__type');
        $this->addSql('DROP TABLE voc__p__base_shape');
        $this->addSql('DROP TABLE voc__p__body');
        $this->addSql('DROP TABLE voc__p__colour');
        $this->addSql('DROP TABLE voc__p__fabric');
        $this->addSql('DROP TABLE voc__p__firing');
        $this->addSql('DROP TABLE voc__p__handle');
        $this->addSql('DROP TABLE voc__p__manufacturing_technique');
        $this->addSql('DROP TABLE voc__p__neck');
        $this->addSql('DROP TABLE voc__p__neck_length');
        $this->addSql('DROP TABLE voc__p__preservation');
        $this->addSql('DROP TABLE voc__p__rim_characterization');
        $this->addSql('DROP TABLE voc__p__rim_direction');
        $this->addSql('DROP TABLE voc__p__rim_shape');
        $this->addSql('DROP TABLE voc__p__size_group');
        $this->addSql('DROP TABLE voc__p__spout');
        $this->addSql('DROP TABLE voc__p__surface_characteristic');
        $this->addSql('DROP TABLE voc__p__surface_treatment');
        $this->addSql('DROP TABLE voc__p__vessel_shape');
        $this->addSql('DROP TABLE voc__p__ware');
        $this->addSql('DROP TABLE voc__period');
        $this->addSql('DROP TABLE voc__preservation_state');
        $this->addSql('DROP TABLE voc__s__type');
        $this->addSql('DROP TABLE voc__su__relationship');
        $this->addSql('DROP TABLE voc__su__type');
    }
}
