controllers:
    resource: ../src/Controller/
    type: annotation

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /app/
        permanent: true

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/login
    methods: ['POST']

change_password:
    path: /api/me/change-password
    controller: App\Controller\ChangePasswordController
    methods: ['POST']

api_refresh_token:
    path: /api/token/refresh
    methods: ['POST']

api_token_invalidate:
    path: /api/token/invalidate
    methods: ['POST']
